Repository department-of-veterans-affairs/caseflow-efolder, pull requests merged in 2020-05, with the labels that each got.

#1222 Prevent exception after semaphore failure
  app/services/record_fetcher.rb
Labels: Source: Sentry Alert

#1233 Upgrade Rails to 5.2.4.3
  Gemfile
  Gemfile.lock
Labels: Type: Tech-Improvement

#1235 Upgrade postgres 11.7
  .circleci/config.yml
  docker-compose.yml
Labels: Ready-to-Merge

#1224 Remove v1 code
  app/controllers/api/v1/documents_controller.rb
  app/controllers/api/v1/files_controller.rb
  app/controllers/application_controller.rb
  app/controllers/downloads_controller.rb
  app/controllers/errors_controller.rb
  app/controllers/health_checks_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/stats_controller.rb
  app/helpers/application_helper.rb
  app/jobs/download_all_manifest_job.rb
  app/jobs/download_files_job.rb
  app/jobs/download_manifest_job.rb
  app/jobs/download_vbms_manifest_job.rb
  app/jobs/download_vva_manifest_job.rb
  app/jobs/restart_stalled_downloads_job.rb
  app/models/document.rb
  app/models/download.rb
  app/models/fetcher.rb
  app/models/search.rb
  app/models/serializers/v1/document_serializer.rb
  app/models/serializers/v1/download_serializer.rb
  app/models/stats.rb
  app/services/download_documents.rb
  app/views/downloads/_confirm.html.erb
  app/views/downloads/_confirm_download_anyway_modal.html.erb
  app/views/downloads/_progress.html.erb
  app/views/downloads/_user_header.html.erb
  app/views/downloads/new.html.erb
  app/views/downloads/not_found.html.erb
  app/views/downloads/show.html.erb
  app/views/stats/show.html.erb
  config/routes.rb
  spec/features/application_helper_spec.rb
  spec/features/dashboard_spec.rb
  spec/features/download_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/jobs/download_all_manifest_job_spec.rb
  spec/jobs/download_vva_manifest_job_spec.rb
  spec/jobs/save_files_in_s3_spec.rb
  spec/models/document_spec.rb
  spec/models/download_spec.rb
  spec/models/fetcher_spec.rb
  spec/models/search_spec.rb
  spec/models/stats_spec.rb
  spec/requests/api/v1/documents_spec.rb
  spec/requests/api/v1/file_spec.rb
  spec/services/download_documents_spec.rb
Labels: Product: caseflow-eFolder-Express, Type: Tech-Improvement
